// Word bank owned by the server (authoritative).
// Categories are stable keys (translated client-side). Words are Polish.
// The impostor hint is a single word that is only obliquely/loosely related to
// the secret word — a vague nudge in the right neighbourhood, never a direct
// description. It should let the impostor bluff without handing them the answer.

export const WORD_BANK: Record<string, { word: string; hint: string }[]> = {
  animals: [
    { word: "DELFIN", hint: "Akrobata" },
    { word: "PINGWIN", hint: "Frak" },
    { word: "KAMELEON", hint: "Maskarada" },
    { word: "KANGUR", hint: "Boks" },
    { word: "OŚMIORNICA", hint: "Atrament" },
    { word: "GEPARD", hint: "Pościg" },
    { word: "FLAMING", hint: "Balet" },
    { word: "SOWA", hint: "Mądrość" },
    { word: "NIETOPERZ", hint: "Echo" },
    { word: "JEŻ", hint: "Kłębek" },
    { word: "WIEWIÓRKA", hint: "Zapasy" },
    { word: "WILK", hint: "Księżyc" },
    { word: "LIS", hint: "Spryt" },
    { word: "SŁOŃ", hint: "Pamięć" },
    { word: "KROKODYL", hint: "Łzy" },
    { word: "ŻABA", hint: "Książę" },
    { word: "MOTYL", hint: "Przemiana" },
    { word: "PAJĄK", hint: "Sieć" },
    { word: "ORZEŁ", hint: "Godło" },
    { word: "KOŃ", hint: "Podkowa" },
  ],
  food: [
    { word: "SUSHI", hint: "Pałeczki" },
    { word: "AWOKADO", hint: "Toast" },
    { word: "CROISSANT", hint: "Półksiężyc" },
    { word: "RAMEN", hint: "Para" },
    { word: "TRUFLA", hint: "Świnia" },
    { word: "MANGO", hint: "Słońce" },
    { word: "PRECEL", hint: "Węzeł" },
    { word: "PIZZA", hint: "Trójkąt" },
    { word: "LODY", hint: "Lato" },
    { word: "CZEKOLADA", hint: "Pokusa" },
    { word: "KAWA", hint: "Poranek" },
    { word: "SER", hint: "Mysz" },
    { word: "PIEROGI", hint: "Babcia" },
    { word: "ARBUZ", hint: "Plaża" },
    { word: "CHILI", hint: "Ogień" },
    { word: "MIÓD", hint: "Niedźwiedź" },
    { word: "POPCORN", hint: "Kino" },
    { word: "SPAGHETTI", hint: "Widelec" },
    { word: "CYTRYNA", hint: "Grymas" },
    { word: "NALEŚNIK", hint: "Rulon" },
  ],
  objects: [
    { word: "TELESKOP", hint: "Daleko" },
    { word: "KOMPAS", hint: "Zgubiony" },
    { word: "KLEPSYDRA", hint: "Przemijanie" },
    { word: "MIKROSKOP", hint: "Szczegół" },
    { word: "MASZYNA DO PISANIA", hint: "Retro" },
    { word: "KALEJDOSKOP", hint: "Symetria" },
    { word: "TERMOMETR", hint: "Gorączka" },
    { word: "PARASOL", hint: "Kałuża" },
    { word: "ŚWIECA", hint: "Urodziny" },
    { word: "LUSTRO", hint: "Próżność" },
    { word: "KOTWICA", hint: "Tatuaż" },
    { word: "GLOBUS", hint: "Podróż" },
    { word: "ŻARÓWKA", hint: "Pomysł" },
    { word: "DRABINA", hint: "Pech" },
    { word: "GRAMOFON", hint: "Nostalgia" },
    { word: "LORNETKA", hint: "Opera" },
    { word: "KLUCZ", hint: "Sekret" },
    { word: "MAPA", hint: "Skarb" },
    { word: "ZEGAR", hint: "Wahadło" },
    { word: "LATARNIA MORSKA", hint: "Samotność" },
  ],
  places: [
    { word: "KOLOSEUM", hint: "Lew" },
    { word: "AMAZONIA", hint: "Tlen" },
    { word: "SAHARA", hint: "Miraż" },
    { word: "ANTARKTYDA", hint: "Cisza" },
    { word: "WERSAL", hint: "Lustro" },
    { word: "DOLINA KRZEMOWA", hint: "Garaż" },
    { word: "STONEHENGE", hint: "Zagadka" },
    { word: "WENECJA", hint: "Maska" },
    { word: "PIRAMIDY", hint: "Klątwa" },
    { word: "WIEŻA EIFFLA", hint: "Oświadczyny" },
    { word: "HOLLYWOOD", hint: "Gwiazda" },
    { word: "BIEGUN PÓŁNOCNY", hint: "Renifer" },
    { word: "CHIŃSKI MUR", hint: "Kosmos" },
    { word: "WULKAN", hint: "Pompeje" },
    { word: "RAFA KORALOWA", hint: "Nemo" },
    { word: "BIBLIOTEKA", hint: "Szept" },
    { word: "ZAMEK", hint: "Duch" },
    { word: "METRO", hint: "Tłok" },
    { word: "OAZA", hint: "Wytchnienie" },
    { word: "EVEREST", hint: "Szerpa" },
  ],
  professions: [
    { word: "SOMELIER", hint: "Nos" },
    { word: "TAKSYDERMISTA", hint: "Trofeum" },
    { word: "AKTUARIUSZ", hint: "Tabela" },
    { word: "ŚLUSARZ", hint: "Awaria" },
    { word: "KARTOGRAF", hint: "Granica" },
    { word: "TŁUMACZ", hint: "Most" },
    { word: "ARCHEOLOG", hint: "Pył" },
    { word: "STRAŻAK", hint: "Kalendarz" },
    { word: "PILOT", hint: "Chmury" },
    { word: "NUREK", hint: "Wrak" },
    { word: "ZEGARMISTRZ", hint: "Cierpliwość" },
    { word: "OGRODNIK", hint: "Wiosna" },
    { word: "ILUZJONISTA", hint: "Rękaw" },
    { word: "LISTONOSZ", hint: "Pies" },
    { word: "DENTYSTA", hint: "Lęk" },
    { word: "PSZCZELARZ", hint: "Dym" },
    { word: "KOMINIARZ", hint: "Szczęście" },
    { word: "ASTRONAUTA", hint: "Nieważkość" },
    { word: "GÓRNIK", hint: "Kanarek" },
    { word: "WETERYNARZ", hint: "Łapa" },
  ],
  plants: [
    { word: "BAMBUS", hint: "Panda" },
    { word: "MUCHOŁÓWKA", hint: "Pułapka" },
    { word: "KAKTUS", hint: "Wytrwałość" },
    { word: "ORCHIDEA", hint: "Elegancja" },
    { word: "NAMORZYN", hint: "Błoto" },
    { word: "LOTOS", hint: "Medytacja" },
    { word: "BAOBAB", hint: "Wiek" },
    { word: "SŁONECZNIK", hint: "Obraz" },
    { word: "RÓŻA", hint: "Walentynki" },
    { word: "DĄB", hint: "Wieczność" },
    { word: "WIERZBA", hint: "Smutek" },
    { word: "PAPROĆ", hint: "Noc" },
    { word: "TULIPAN", hint: "Mania" },
    { word: "BLUSZCZ", hint: "Mur" },
    { word: "WINOROŚL", hint: "Bachus" },
    { word: "SOSNA", hint: "Święta" },
    { word: "MNISZEK", hint: "Życzenie" },
    { word: "OLIWKA", hint: "Pokój" },
    { word: "POKRZYWA", hint: "Zupa" },
    { word: "WAWRZYN", hint: "Zwycięstwo" },
  ],
};

const CATEGORIES = Object.keys(WORD_BANK);

export function pickRandomWord() {
  const category = CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)];
  const words = WORD_BANK[category];
  const entry = words[Math.floor(Math.random() * words.length)];
  return { category, word: entry.word, hint: entry.hint };
}

// Word pairs for "undercover" mode: two similar-but-distinct words. The crew all
// get one word, the undercover(s) get the other. Clues overlap heavily, so the
// tell is subtle — that's the whole game. Order within a pair is irrelevant; the
// engine randomly decides which side is the crew word.
export const WORD_PAIRS: [string, string][] = [
  ["HERBATA", "KAWA"],
  ["LEW", "TYGRYS"],
  ["PIES", "WILK"],
  ["GITARA", "SKRZYPCE"],
  ["ROWER", "MOTOCYKL"],
  ["JEZIORO", "MORZE"],
  ["KSIĄŻKA", "GAZETA"],
  ["LATO", "WIOSNA"],
  ["ŚNIEG", "DESZCZ"],
  ["ZAMEK", "PAŁAC"],
  ["SAMOLOT", "HELIKOPTER"],
  ["JABŁKO", "GRUSZKA"],
  ["KOT", "RYŚ"],
  ["PIWO", "WINO"],
  ["TELEFON", "TABLET"],
  ["RZEKA", "STRUMIEŃ"],
  ["GÓRY", "WZGÓRZA"],
  ["MALARZ", "RYSOWNIK"],
  ["LEKARZ", "PIELĘGNIARKA"],
  ["MASŁO", "MARGARYNA"],
  ["SOK", "LEMONIADA"],
  ["KRZESŁO", "FOTEL"],
  ["DŁUGOPIS", "OŁÓWEK"],
  ["ZEGAR", "ZEGAREK"],
  ["STATEK", "ŁÓDŹ"],
  ["AUTOBUS", "TRAMWAJ"],
  ["ŚWIECA", "LAMPA"],
  ["KAPELUSZ", "CZAPKA"],
  ["BUTY", "KAPCIE"],
  ["SŁOŃCE", "KSIĘŻYC"],
  ["CYRK", "TEATR"],
  ["ZUPA", "SOS"],
  ["TRUSKAWKA", "MALINA"],
  ["CYTRYNA", "LIMONKA"],
  ["WĄŻ", "JASZCZURKA"],
  ["MOTYL", "ĆMA"],
  ["PSZCZOŁA", "OSA"],
  ["KROKODYL", "ALIGATOR"],
  ["DELFIN", "REKIN"],
  ["SKARPETKI", "RAJSTOPY"],
  ["NARTY", "SNOWBOARD"],
  ["PIANINO", "ORGANY"],
  ["KOMETA", "METEOR"],
  ["MGŁA", "CHMURA"],
];

/** Pick a pair and randomly assign crew word vs. undercover word. */
export function pickRandomPair(): { crewWord: string; undercoverWord: string } {
  const pair = WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
  const flip = Math.random() < 0.5;
  return flip
    ? { crewWord: pair[0], undercoverWord: pair[1] }
    : { crewWord: pair[1], undercoverWord: pair[0] };
}
